<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use DB;
class chenPhuong extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('Phuong')->insert([
            ['Ten_Phuong' => 'Phường Tân Định', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Đa Kao', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Bến Nghé', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Bến Thành', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Nguyễn Thái Bình', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Phạm Ngũ Lão', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Cầu Ông Lãnh', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Cô Giang', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Nguyễn Cư Trinh', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Cầu Kho', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Thạnh Xuân', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Thạnh Lộc', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Hiệp Thành', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Thới An', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Tân Chánh Hiệp', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường An Phú Đông', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Tân Thới Hiệp', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Trung Mỹ Tây', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Tân Hưng Thuận', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Đông Hưng Thuận', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Tân Thới Nhất', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Linh Xuân', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Bình Chiểu', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Linh Trung', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Tam Bình', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Tam Phú', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Hiệp Bình Phước', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Hiệp Bình Chánh', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Linh Chiểu', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Linh Tây', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Linh Đông', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Bình Thọ', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Trường Thọ', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Long Bình', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Long Thạnh Mỹ', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Tân Phú', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Hiệp Phú', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Tăng Nhơn Phú A', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Tăng Nhơn Phú B', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Phước Long B', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Phước Long A', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Trường Thạnh', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Long Phước', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Long Trường', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Phước Bình', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Phú Hữu', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường 1', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường 2', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường 3', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường 4', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường 5', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường 6', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường 7', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường 8', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường 9', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường 10', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường 11', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường 12', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường 13', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường 14', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường 15', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường 16', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường 17', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường 18', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường 19', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường 20', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường 21', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường 22', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường 23', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường 24', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường 25', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường 26', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường 27', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường 28', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Tân Sơn Nhì', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Tây Thạnh', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Sơn Kỳ', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Tân Qúy', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Tân Thành', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Phú Thọ Hoà', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Phú Thạnh', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Phú Trung', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Hoà Thạnh', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Hiệp Tân', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Tân Thới Hoà', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Thảo Điền', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường An Phú', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Bình An', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Bình Trưng Đông', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Bình Trưng Tây', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Bình Khánh', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường An Khánh', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Cát Lái', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Thạnh Mỹ Lợi', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường An Lợi Đông', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Thủ Thiêm', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Bình Hưng Hòa', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Bình Hưng Hoà A', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Bình Hưng Hoà B', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Bình Trị Đông', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Bình Trị Đông A', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Bình Trị Đông B', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Tân Tạo', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Tân Tạo A', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường An Lạc', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường An Lạc A', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Tân Thuận Đông', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Tân Thuận Tây', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Tân Kiểng', 'AnHien' => 1],            
            ['Ten_Phuong' => 'Phường Tân Hưng', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Bình Thuận', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Tân Quy', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Phú Thuận', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Tân Phú', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Tân Phong', 'AnHien' => 1],
            ['Ten_Phuong' => 'Phường Phú Mỹ', 'AnHien' => 1],
            ['Ten_Phuong' => 'Thị trấn Củ Chi', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Phú Mỹ Hưng', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã An Phú', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Trung Lập Thượng', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã An Nhơn Tây', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Nhuận Đức', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Phạm Văn Cội', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Phú Hòa Đông', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Trung Lập Hạ', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Trung An', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Phước Thạnh', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Phước Hiệp', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Tân An Hội', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Phước Vĩnh An', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Thái Mỹ', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Tân Thạnh Tây', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Hòa Phú', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Tân Thạnh Đông', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Bình Mỹ', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Tân Phú Trung', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Tân Thông Hội', 'AnHien' => 1],
            ['Ten_Phuong' => 'Thị trấn Hóc Môn', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Tân Hiệp', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Nhị Bình', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Đông Thạnh', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Thới Tam Thôn', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Xuân Thới Sơn', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Tân Xuân', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Xuân Thới Đông', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Trung Chánh', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Xuân Thới Thượng', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Bà Điểm', 'AnHien' => 1],
            ['Ten_Phuong' => 'Thị trấn Tân Túc', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Phạm Văn Hai', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Vĩnh Lộc A', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Vĩnh Lộc B', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Bình Lợi', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Lê Minh Xuân', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Tân Nhựt', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Tân Kiên', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Bình Hưng', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Phong Phú', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã An Phú Tây', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Hưng Long', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Đa Phước', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Tân Quý Tây', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Bình Chánh', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Quy Đức', 'AnHien' => 1],
            ['Ten_Phuong' => 'Thị trấn Nhà Bè', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Phước Kiển', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Phước Lộc', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Nhơn Đức', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Hiệp Phước', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Phú Xuân', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Long Thới', 'AnHien' => 1],
            ['Ten_Phuong' => 'Thị trấn Cần Thạnh', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Bình Khánh', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Tam Thôn Hiệp', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã An Thới Đông', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Thạnh An', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Long Hòa', 'AnHien' => 1],
            ['Ten_Phuong' => 'Xã Lý Nhơn', 'AnHien' => 1],
        ]);
    }
}
